// <auto-generated />
namespace CodeWarrior2015.Backend.Service.ProductCRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ProductUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201501261532009_ProductUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
