// <auto-generated />
namespace CW.Backend.DAL.CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ProductOrderM2M : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductOrderM2M));
        
        string IMigrationMetadata.Id
        {
            get { return "201501301628356_ProductOrderM2M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
